# ======================================================================================================================
#                                               Evoparty Configuration File
# ======================================================================================================================

MaxPartySize: 5
# Controls the max party size.
# Take care not to make this value too high as it could create problems with the party HUD
# Default is 5

PermissionBasedParties: false
# When set to true players must have the correct permissions to create/manage parties
# evoparty.* = Grants all permissions related to evoparty
# evoparty.start = allows a player to start a party
# evoparty.invite = allows a player to invite another player to a party
# evoparty.teleport = allows a player to teleport to other players within the party
# evoparty.teleportall = allows a payer to teleport the entire party to them
# evoparty.hud = allows a player to toggle their HUD
# evoparty.partychat = allows a player to use party chat

AllowHudToggle: true
# Allow players to individually toggle their HUD.
# HUD toggling can be allowed on a per user basis by using the permissions listed above.
# Turning off the HUD in a party will cause friendly fire to be enabled!

FriendlyFire: false
# Allow or Deny friendly fire. Disabled by default.